### PR TITLE
Bumped breeze version

### PR DESCRIPTION
**Pull request by superbobry**
Relevant changes for us:

scalanlp/breeze@dc4e0057ebc73a0308c51fb791f2cd11fba3ed22
scalanlp/breeze@5ae0579db1711df3599383419dcb6a27450826d4
scalanlp/breeze@c3ff07a10a502eba6a6c560f60a036cbbe855294

### CODE REVIEW

**Comment by bloody76** [comment]
Can you explain more why we need to bump the version ?

**Review by bloody76 — APPROVED** [review]
Seems ok to me.

**Comment by ashangit** [comment]
@superbobry as we want to avoid diverging too much from apache spark do we have a request open on the spark jira for this bumped version (at least for spark 2.1)

**Comment by superbobry** [comment]
@ashangit that's a valid point. I'll try to push that upstream first.

**Update**: there is an upstream PR merged into 2.2: apache/spark#17746. Do you think we should backport it instead?

**Comment by ashangit** [comment]
@superbobry yes I think that it will be better as it seems that the bump also imply some changes on some ml lib/tests.
Would be great then to push back the backport (for 2.1) to the spark community.

By the way for future PR we do not need to have them pushed upstream first but to have a jira reference on the upstream project for the PR to ensure a work is ongoing to push the PR upstream.

**Comment by AnthonyTruchet** [comment]
Could you please link here to the upstream patch ?

**Comment by superbobry** [comment]
> Would be great then to push back the backport (for 2.1) to the spark community.

I've asked upstream, why they didn't merge into 2.1. If they don't want it because of compatibility reasons, than we would have to merge it into Criteo fork bypassing upstream.

> Could you please link here to the upstream patch?

Sure, there is a link in the above comment: apache/spark#17746.

**Comment by superbobry** [comment]
So the bottomline is: 2.1 would not get the new breeze because of backward-incompatible API changes.

I think we should better wait until 2.2 instead of backporting the patch into 2.1.

**Comment by ashangit** [comment]
That's fine for me.
You should just know that spark 2.2 should not support scala 2.10 and I don't know when we will migrate to 2.11 so spark 2.2 could take some while to be available in our platform

**Pull request closed without merging**
